[flags]
current_usage = true
default_widget_type = "proc"
# dot_marker = true

[[row]]
  [[row.child]]
  type="cpu"
  [[row.child]]
  type="net"
[[row]]
    ratio=3
    [[row.child]]
      ratio=4
      type="proc"
    [[row.child]]
      ratio=2
      [[row.child.child]]
        ratio=3
        type="mem"
      [[row.child.child]]
        ratio=2
        type="temp"
      [[row.child.child]]
        ratio=2
        type="disk"
