#!/bin/sh

export JAVA_HOME=~/.sdkman/candidates/java/21.0.2-tem
[ ! -d "$JAVA_HOME" ] && echo "$JAVA_HOME not a valid directory!, exitting" && exit 1

if [ "$1" = "mason" ]; then # mason injects it's bin dir into PATH of nvim runtime, where jdtls will be
    jdtls
else
    if [ "$(uname)" = "Darwin" ]; then
        /opt/homebrew/bin/jdtls     # assume homebrew install for OSX
    else
        ~/src/jdtls/bin/jdtls    # otherwise assume linux, manual d/l of jdtls
    fi
fi
