#!/bin/sh

# pass noreset=1 and empty/no string to format external string
# TODO: validate fg and bg values, after ansi8 translation values must be numbers 1-250

ansi8_name () {
    case "$1" in
        red) echo 1 ;; brightred) echo 9 ;;
        green) echo 2 ;; brightgreen) echo 10 ;;
        yellow) echo 3 ;; brightyellow) echo 11 ;;
        blue) echo 4 ;; brightblue) echo 12 ;;
        magenta) echo 5 ;; brightmagenta) echo 13 ;;
        cyan) echo 6 ;; brightcyan) echo 14 ;;
        white) echo 7 ;; brightwhite) echo 15 ;;
        black) echo 8 ;; brightblack) echo 16 ;;   # should really call it dark black, it's 100% black
        *) echo $1 ;;
    esac
}

# TODO: remove callers that use these vars with using optargs
maybereset="\033[0m"; [ -n "$noreset" ] && maybereset=""
maybestrike="";       [ -n "$strike" ] && maybestrike="\033[9m"
maybebld="";          [ -n "$bld" ] && maybebld="\033[1m"
maybeund="";          [ -n "$und" ] && maybeund="\033[4m"
maybeit="";           [ -n "$it" ] && maybeit="\033[3m"
maybeinverse="";      [ -n "$inv" ] && maybeinverse="\033[7m"
lbg=016;              [ -n "$bg" ] && lbg=$(ansi8_name $bg)
lfg=007;              [ -n "$fg" ] && lfg=$(ansi8_name $fg)

usage () { echo "Usage: [ -h(help) ] [ -f FOREGROUND_COLOR ] [ -b BACKGROUND_COLOR ] [ -i(italics) ] [ -u(underline) ] [ -s(strikethrough) ] [ -r(no reset) ] [ -e(bold) ] [ -n(inverse) ]"; }

while getopts 'f:b:heiusnr' x; do
    case $x in
        f) lfg=$(ansi8_name "$OPTARG") ;;
        b) lbg=$(ansi8_name "$OPTARG") ;;
        h) usage && exit 1 ;;
        i) maybeit="\033[3m" ;;
        e) maybebld="\033[1m" ;;
        u) maybeund="\033[4m" ;;
        s) maybestrike="\033[9m" ;;
        r) maybereset="" ;;
        n) maybeinverse="\033[7m" ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

# zsh, osx /bin/sh, dash always expand escape sequences, bash does not and needs -e option
echo "${maybeinverse}${maybebld}${maybestrike}${maybeund}${maybeit}\033[48;5;${lbg};38;5;${lfg}m${1}${maybereset}"
