#!/bin/sh

# TODO: dash doesnt like something in shell_function.sh (nov11 2020)
. ~/rams_dot_files/shell_functions.sh

caller=$0 cmds_defined readlink ansi256 || exit 1

binlinksfile=${blfile:-~/rams_dot_files/bin_links.txt}
bindir=~/bin
[ ! -f "$binlinksfile" ] && echo "file $binlinksfile NOT found!" && exit 1

while read entry; do
    binlinkname=$(echo "$entry" | awk '{print $1}')
    expectedlinktarget=$(echo "$entry" | awk '{print $2}')
    eval expectedlinktarget=$expectedlinktarget  # will expand "~"
    symlink="${bindir}/${binlinkname}"
    linktarget=$(readlink "$symlink")
    [ -n "$verbose" ] && echo "Checking: "$(fg=yellow ansi256 "$binname")
    if [ ! -L "${symlink}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")$(fg=red ansi256 ": symlink doesnt exist in ${bindir}")
    elif [ ! -f "${symlink}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")$(fg=red ansi256 ": symlink pointing to nonexistent file")
    elif [ ! -x "${symlink}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")$(fg=red ansi256 ": symlink pointing to nonexecutable file")
    elif [ "${linktarget}" != "${expectedlinktarget}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")\
            $(fg=red ansi256 "points to ${linktarget}, should point to ${expectedlinktarget}")
    fi

done<"$binlinksfile"
