#!/bin/sh

# bin-link-checker - verify that file defining synlinks to executables exist and are valid

usage () { echo "Usage: bin-link-checker [ -h(help) ] [ -v(verbose) ]"; }

while getopts 'vh' x; do
    case $x in
        v)  verbose=1 ;;
        h) usage && exit 1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

. ~/rams_dot_files/shell_core_tools.sh || { echo "could not find shell_core_tools.sh" && exit 1; }

caller=$0 cmds_defined readlink ansi256 || exit 1

binlinksfile=${BIN_LINKS_FILE:-~/rams_dot_files/bin_links.txt}
bindir=~/bin
[ ! -f "$binlinksfile" ] && echo "file $(ansi256 -f red "$binlinksfile") NOT found!" && exit 1

echo "reading bin links from file $(ansi256 -f yellow $binlinksfile)"
echo ""

while read entry; do
    binlinkname=$(echo "$entry" | awk '{print $1}')
    expectedlinktarget=$(echo "$entry" | awk '{print $2}')
    eval expectedlinktarget=$expectedlinktarget  # will expand "~"
    symlink="${bindir}/${binlinkname}"
    linktarget=$(readlink "$symlink")
    [ -n "$verbose" ] && echo "Checking: "$(ansi256 -f yellow "$binlinkname")
    if [ ! -L "${symlink}" ]; then
        echo $(ansi256 -e -f red "${binlinkname}")$(ansi256 -f red ": symlink doesnt exist in ${bindir}")
    elif [ ! -f "${symlink}" ]; then
        echo $(ansi256 -e -f red "${binlinkname}")$(ansi256 -f red ": symlink pointing to nonexistent file")
    elif [ ! -x "${symlink}" ]; then
        echo $(ansi256 -f red -e "${binlinkname}")$(ansi256 -f red ": symlink pointing to nonexecutable file")
    elif [ "${linktarget}" != "${expectedlinktarget}" ]; then
        echo $(ansi256 -f red -e "${binlinkname}")\
            $(ansi256 -f red "points to ${linktarget}, should point to ${expectedlinktarget}")
    fi

done<"$binlinksfile"
