#!/bin/sh

source ~/rams_dot_files/shell_functions.sh

binlinksfile=${blfile:-~/rams_dot_files/bin_links.txt}
bindir=~/bin
sourcedir=~/rams_dot_files/scripts
[ ! -f "$binlinksfile" ] && echo "file $binlinksfile NOT found!" && exit 1

while read binname; do
    echo $binname
    if [ ! -f "$bindir/$binname" -o ! -x "${sourcedir}/${binname}" ]; then
        echo $(fg=red ansi256 "${binname} not linked in ${bindir} or no executable in ${sourcedir}")
    fi
done<"$binlinksfile"
