#!/bin/sh

# TODO: check if symlink is valid

# TODO: dash doesnt like something in shell_function.sh (nov11 2020)
. ~/rams_dot_files/shell_functions.sh

cmds_defined readlink ansi256 || exit 1

binlinksfile=${blfile:-~/rams_dot_files/bin_links.txt}
bindir=~/bin
sourcedir=~/rams_dot_files/scripts
[ ! -f "$binlinksfile" ] && echo "file $binlinksfile NOT found!" && exit 1

while read binname; do
    symlink="${bindir}/${binname}"
    linktarget=$(readlink "$symlink")
    expectedlinktarget="${sourcedir}/${binname}"
    [ -n "$verbose" ] && echo "Checking: "$(fg=yellow ansi256 "$binname")
    if [ ! -L "${symlink}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")$(fg=red ansi256 ": symlink doesnt exist in ${bindir}")
    elif [ ! -f "${symlink}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")$(fg=red ansi256 ": symlink pointing to nonexistent file")
    elif [ ! -x "${symlink}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")$(fg=red ansi256 ": symlink pointing to nonexecutable file")
    elif [ "${linktarget}" != "${expectedlinktarget}" ]; then
        echo $(fg=red bld=1 ansi256 "${binname}")\
            $(fg=red ansi256 "points to ${linktarget}, should point to ${expectedlinktarget}")
    fi

done<"$binlinksfile"
