#!/bin/sh

[ ! "$(uname)" = "Darwin" ] && echo "RLY-ERROR: chrome-json-summary needs applescript, only Darwin os" >&2 && exit 1

usage () { echo "Usage: chrome-save-state [ -h(help) ] [ -s(summary only) ] "; }

while getopts 'hs' x; do
    case $x in
        h) usage && exit 1 ;;
        s) SUMMARY_ONLY=1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

chrome_json_summary() {
    wincount=$(osascript -e 'tell application "Google Chrome" to get number of windows')
    [ "$wincount" -eq 0 ] && echo "zero windows!" && return

    json="["
    for (( i=1; i<=$wincount; i++)); do
        json="$json""["
        cmd="osascript -e 'tell application \"Google Chrome\" to get number of tabs in window $i'"
        tabcount=$(eval $cmd)
        for (( j=1; j<=$tabcount; j++)); do
            #osascript -e 'tell application "Google Chrome" to get {URL,title} of tab 1 of window 1'
            cmd="osascript -e 'tell application \"Google Chrome\" to get URL of tab $j of window $i'"
            url=$(eval $cmd)
            [ $j -eq $tabcount ] && json="$json\"$url\"" || json="$json\"$url\","
        done
        [ $i -eq $wincount ] && json="$json]" || json="$json],"
    done
    echo "$json]"
}

if [ -z "$SUMMARY_ONLY" ]; then
    echo $(chrome_json_summary) > ~/Documents/chrome_tabs_backup.json
else
    chrome_json_summary
fi
