#!/bin/sh

# colorize every 3rd line lighter background (assuming black background) to help readability

usage () { echo "Usage: colr-row [ -h(help) ] [ -v(verbose) ] [ -b(bright) ] "; }

while getopts 'hbv' x; do
    case $x in
        h) usage && exit 1 ;;
        b) BRIGHT=1 ;;
        v) VERBOSE=1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

NUM_COLS=$(tput cols)
[ -n "$VERBOSE" ] && echo "COLUMN WIDTH: $NUM_COLS" && echo

padding() {
    LINE_SIZE=$1
    # echo "LINE SIZE: $LINE_SIZE"

    REMAINDER=$(($LINE_SIZE % $NUM_COLS))
    PADDING=$(($NUM_COLS - $REMAINDER))
    # echo "PADDING: $PADDING"
    for i in $(seq 1 $PADDING); do
        printf ' %.0s'
    done
    # printf ' %.0s' {1..$PADDING}  # doesnt work with ubuntu sh(dash), {x..y} syntax not supported
}

# read command by default removes leading and trailing spaces, set IFS to preserve them
while IFS= read line; do
    if [ -z "$BRIGHT" ]; then
        size=$(echo "$line" | wc -c)
        pad="$(padding $size)"
        ansi256 -b 237 "$line$pad"
    else
        size=$(echo "$line" | wc -c)
        pad="$(padding $size)"
        ansi256 -n "$line$pad"
    fi
    IFS= read line; echo "$line"; IFS= read line; echo "$line"
done
