#!/bin/sh

# TODO: need to make ctag_create a script

# TODO: dash doesnt like something in shell_function.sh (nov11 2020)
source ~/rams_dot_files/shell_functions.sh

caller=$0 cmds_defined ansi256 ctag_create || exit 1

commit=$(git rev-parse HEAD 2>&1) || { echo $(fg=red ansi256 "pwd: $(pwd), NOT a git repo!") && exit 1; }
[ ! -d .git ] && { echo $(fg=red ansi256 "NOT at base of git repo!") && exit 1; }

create_msg=$(fg=yellow ansi256 "writing ctag file")
if [ -f ctag_git_ver -a -f tags ]; then
    if [ "$(cat ctag_git_ver)" = "$commit" ]; then
        [ -n "$verbose" ] && echo $(fg=yellow ansi256 "commit $commit matches, ctags not updated")
    else
        [ -n "$verbose" ] && echo $(fg=red ansi256 "commit $commit DOES NOT match, ")"$create_msg"
        ctag_create
        echo ${commit} > ctag_git_ver
    fi
else
    [ -n "$verbose" ] && echo $(fg=red ansi256 "NO tags or ctag_git_ver file, ")"$create_msg"
    ctag_create
    echo ${commit} > ctag_git_ver
fi
