#!/bin/sh

[ -z "$1" ] && echo "no message given!" && exit 1
if [ $(uname) = "Darwin" ]; then
    # osascript -e 'display notification "hi!" with title "my title" subtitle "a subtitle"'
    script="display notification \"$1\""
    title=${2:-notification}
    script=$script" with title \"$title\""
    osascript -e "$script"
else  # really for ubuntu
    title=${2:-notitle}
    notify-send -i face-wink "$title" "$1"
fi
