#!/bin/sh

# FIXME: many packages are not seperated with `,`, often space

# APT + FZF
usage () { echo 'Usage: fapt [ -h(help) [ -i(just installed) ] [ -f(fzf half screen) ]'; }

FZF_HEIGHT=100
while getopts 'hif' x; do
    case $x in
        h) usage && exit 1 ;;
        i) opts="--installed" ;;
        f) FZF_HEIGHT=50 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

apt list $opts | tail -n+2 |
    fzf --height "$FZF_HEIGHT"% --preview 'pkg=$(awk "{print  $1}" <<< {} | cut -d "," -f1); echo $pkg; apt show $pkg; echo; apt depends $pkg'
