#!/bin/sh

# FZF + bluetoothctl

[ ! "$(uname)" = "Linux" ] && echo "$(tput setaf 1) Only works in Linux" && exit 1

header="ctrl-r->reload devices,
ctrl-space->reload paired-devices,
ctrl-s->reload connected devices,
ctrl-o->connect, ctrl-i->disconnect,
enter->info"

prev_cmd='bluetoothctl info $(awk '\''{print $2}'\'' <<< {})'
out=$(bluetoothctl devices | fzf +m --height 100% \
    --preview "$prev_cmd" \
    --header="$header" \
    --bind 'ctrl-r:reload(bluetoothctl devices)' \
    --bind 'ctrl-space:reload(bluetoothctl devices Paired)' \
    --bind 'ctrl-s:reload(bluetoothctl devices Connected)' \
    --expect='ctrl-o,ctrl-i')
key=$(echo "$out" | head -1)
selection=$(echo "$out" | tail -1)
if [ -n "$selection" ]; then
    device=$(echo "$selection" | awk '{print $2}')
    case "$key" in
        "ctrl-o") bluetoothctl connect "$device" ;;
        "ctrl-i") bluetoothctl disconnect "$device" ;;
        *) bluetoothctl info "$device" ;;
    esac
fi
