#!/bin/sh

# FZF + busctl

usage () { echo 'Usage: fdbus [ -h(help) ]'; }

while getopts 'h' x; do
    case $x in
        h) usage && exit 1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

preview_cmd='device=$(echo {} | awk '\''{print $1}'\''); busctl status $device; echo; busctl tree $device'
preview_cmd_2='device=$(echo {} | awk '\''{print $1}'\''); busctl monitor $device'

out=$(busctl | fzf +m --exit-0 --height 100% --header-lines=1 \
    --header='ctrl-s->monitor-events' \
    --bind "ctrl-s:preview(${preview_cmd_2})" \
    --preview "$preview_cmd" \
    --preview-window=:wrap)
