#!/bin/zsh

# FDCOMP - Fzf over docker compose files in a dir and run one

usage () { echo 'Usage: fdcomp [ -h(help) ]'; }

while getopts 'h' x; do
    case $x in
        h) usage && exit 1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

header='ctrl-i->up-detatched, ctrl-e->edit
ctrl-o->pull-image, ctrl-s->down+rmi'

# NOTE: fdfind needs quotes here or 0 matches, in regular zshell it works w/o quotes
out=$(fdfind -t f "compose.*\.yml" | fzf +m --height 100% \
    --header=$'ctrl-i->up-detatched, ctrl-e->edit\nctrl-o->pull-image, ctrl-s->down+rmi' \
    --preview 'batcat --color always {}' \
    --expect='ctrl-i,ctrl-e,ctrl-s,ctrl-o')

key=$(echo "$out" | head -1)
composefile=$(echo "$out" | tail -1)
if [ -n "$composefile" ]; then
    case "$key" in
        "ctrl-i") docker compose -f "$composefile" up -d ;;
        "ctrl-s") docker compose -f "$composefile" down --rmi all ;;
        "ctrl-o") docker compose -f "$composefile" pull ;;
        "ctrl-e") $EDITOR "$composefile" ;;
    esac
fi
