#!/bin/sh

# FF - Fzf on files in a dir with file prev and open or edit or cd to or add to clipboard

usage () { echo "Usage: ff [ -h(help) ] [ -j FZF_HEIGHT ]"; }

while getopts 'hj:' x; do
    case $x in
        h) usage && exit 1 ;;
        j) FZF_HEIGHT="$OPTARG" ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

FDNAME="fd"; [ `uname` = "Linux" ] && FDNAME="fdfind"
FZF_HEIGHT=${FZF_HEIGHT:=100}

fzf_def="$FZF_DEFAULT_COMMAND"
if [ "$1" = "h" ]; then
    fzf_def="$FDNAME --type f --hidden --exclude .git '.*' ~"
elif [ -n "$1" ]; then
    [ ! -d "$1" ] && echo "$1 not a dir!" && return 1
    fzf_def="$FDNAME --type f --hidden --exclude .git '.*' $1"
fi

# TODO: ctrl-space to cd wont work now that this is a script, shell func yea b/c same shell process
out=$(FZF_DEFAULT_COMMAND="$fzf_def" fzf +m --exit-0 --height "$FZF_HEIGHT"% \
    --header='ctrl-i->vim, ctrl-o->open, ctrl-space->cd, ctrl-y->pbcopy' \
    --bind 'ctrl-y:execute-silent(echo {} | pbcopy)+abort' \
    --expect='ctrl-o,ctrl-i,ctrl-space' \
    --preview 'bat --style=numbers --color=always {} | head -500' \
    --preview-window=:wrap)
key=$(echo "$out" | head -1)
file=$(echo "$out" | tail -1)
if [ -n "$file" ]; then
    case "$key" in
        "ctrl-o") open "$file" ;;
        "ctrl-space") cd "$(dirname "$file")" ;;
        "ctrl-i") eval "${EDITOR:-vin} "$file"" ;;
    esac
fi
echo "$file"
