#!/bin/sh

# FFCB (Fzf Chrome Bookmarks)

if [ "$(uname)" = "Darwin" ]; then
    bookmarks_path=~/Library/Application\ Support/Google/Chrome/Default/Bookmarks
else
    bookmarks_path=~/.config/google-chrome/Default/Bookmarks
fi

OPENBIN="open"; [ $(uname) = "Linux" ] && OPENBIN='xdg-open'

jq_script='
    def ancestors: while(. | length >= 2; del(.[-1,-2]));
    . as $in | paths(.url?) as $key | $in | getpath($key) | {name,url, path: [$key[0:-2] | ancestors as $a | $in | getpath($a) | .name?] | reverse | join("/") } | .path + "/" + .name + "\t" + .url'

bookmark=$(jq -r "$jq_script" < "$bookmarks_path" \
    | sed -E $'s/(.*)\t(.*)/\\1\t\x1b[36m\\2\x1b[m/g' \
    | fzf --ansi | cut -f 2)

[ -n "$bookmark" ] && $OPENBIN "$bookmark"
