#!/bin/sh

cols=$(( $(tput cols) / 3 ))
sep='{::}'

if [ "$(uname)" = "Darwin" ]; then
    google_history="$HOME/Library/Application Support/Google/Chrome/Default/History"
    open=open
else
    google_history="$HOME/.config/google-chrome/Default/History"
    open=xdg-open
fi

cp -f "$google_history" /tmp/h
out=$(sqlite3 -separator $sep /tmp/h \
    "select substr(title, 1, $cols), url
     from urls order by last_visit_time desc" |
awk -F $sep '{printf "%-'$cols's  \x1b[36m%s\x1b[m\n", $1, $2}' |
fzf --no-sort --ansi --multi \
    --header='ctrl-u -> open, ctrl-o -> sort' \
    --expect='ctrl-u' \
    --bind 'ctrl-o:toggle-sort')
key=$(echo "$out" | head -1)
histlink=$(echo "$out" | tail -1)
if [ -n "$histlink" ]; then
    case "$key" in
        "ctrl-u") echo "$histlink" | sed 's#.*\(https*://\)#\1#' | xargs $open > /dev/null 2> /dev/null ;;
    esac
fi
echo "$histlink"
