#!/bin/sh

#FIXME: the descriptive name of the history item doesnt appear on the left, i just see the hyperlink

maybesort="--no-sort"; [ -n "$sort" ] && maybesort=""
cols=$(( COLUMNS / 3 ))
sep='{::}'

if [ "$(uname)" = "Darwin" ]; then
    google_history="$HOME/Library/Application Support/Google/Chrome/Default/History"
    open=open
else
    google_history="$HOME/.config/google-chrome/Default/History"
    open=xdg-open
fi
cp -f "$google_history" /tmp/h
sqlite3 -separator $sep /tmp/h \
    "select substr(title, 1, $cols), url
     from urls order by last_visit_time desc" |
awk -F $sep '{printf "%-'$cols's  \x1b[36m%s\x1b[m\n", $1, $2}' |
fzf $maybesort --ansi --multi | sed 's#.*\(https*://\)#\1#' | xargs $open > /dev/null 2> /dev/null
