#!/bin/sh

# FFGB (Fzf Git Branch)

# TODO: add binding to checkout a branch

git rev-parse HEAD > /dev/null 2>&1 || { echo "not git repo" && return 1; }
ht="100%"; [ -n "$half" ] && ht="50%"

git branch -a --color=always | grep -v '/HEAD\s' | sort |
fzf --height $ht --border --ansi --multi --tac --preview-window right:70% \
    --preview 'git log --oneline --graph --date=short --color=always --pretty="format:%C(auto)%cd %h%d %s" $(sed s/^..// <<< {} | cut -d" " -f1) | head -'$LINES  |
sed 's/^..//' | cut -d' ' -f1 | sed 's#^remotes/##'
