#!/bin/sh

# FFGL (Fzf Git Log)

# $1 - optional file to git log on, otherwise while repo commit history
# FIXME: if i multiselect, pbcopy only has one copy
# TODO: add binding to checkout a commit

usage () { echo "Usage: ffgl [ -h(help) ] [ -s(short preview) ]"; }

while getopts 'hs' x; do
    case $x in
        h) usage && exit 1 ;;
        s) SHORT_PREVIEW=1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

git rev-parse HEAD > /dev/null 2>&1 || { echo "not git repo" && return 1; }
[ -n "$1" -a ! -f "$1" ] && echo "file $1 doesnt exist" && return 1
ht="100%"; [ -n "$half" ] && ht="50%"

preview_cmd='cmt=$(grep -o "[a-f0-9]\{7,\}" <<< {}); git show --color=always $cmt '"$@"
[ -n "$SHORT_PREVIEW" ] && preview_cmd="$preview_cmd | head -$(tput lines)"

git log --date=short --format="%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)" --graph --color=always $@ |
fzf --height $ht --border --ansi --no-sort --reverse --multi --bind 'ctrl-s:toggle-sort' \
    --bind 'ctrl-y:execute-silent(grep -o "[a-f0-9]\{7,\}" <<< {} | pbcopy)+abort' \
    --header 'ctrl-s->toggle sort,ctrl-y->pbcopy' --preview-window=:wrap \
    --preview "$preview_cmd" |
grep -o "[a-f0-9]\{7,\}"
