#!/bin/sh

# FGH - Fzf on github pulls in the current repo

usage () { echo "Usage: fgh [ -h(help) ] [ -a(last 300 pulls) ]"; }

while getopts 'ha' x; do
    ALL_OPT=""
    case $x in
        h) usage && exit 1 ;;
        a) ALL_OPT="--state all --limit 300" ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

out=$(gh pr list $ALL_OPT |
    fzf --ansi +m \
        --expect='ctrl-o' \
        --header 'ctrl-o->open-in-web, enter->git-diff' \
        --preview 'echo "CHECKS:"; gh pr checks {1}; echo ""; echo ""; echo "VIEW:"; gh pr view {1}')
key=$(echo "$out" | head -1)
pr=$(echo "$out" | tail -1)
if [ -n "$pr" ]; then
    prnum=$(echo "$pr" | awk '{print $1}')
    case "$key" in
        "ctrl-o") gh pr view --web $prnum ;;
        *) gh pr diff $prnum ;;
    esac
fi
