#!/bin/sh

# FGH - Fzf on github pulls in the current repo

usage () { echo "Usage: fgh [ -h(help) ] [ -c CUSTOM_GH_FILTERS ] [ -a AUTHOR ] [ -s(all states) ]"; }

GH_FILTERS="--limit 300"

while getopts 'hc:a:s' x; do
    case $x in
        h) usage && exit 1 ;;
        c) GH_FILTERS="$OPTARG" ;;
        a) GH_FILTERS="$GH_FILTERS --author $OPTARG" ;;
        s) GH_FILTERS="$GH_FILTERS --state all" ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

out=$(gh pr list $GH_FILTERS |
    fzf --ansi +m \
        --expect='ctrl-o,ctrl-i' \
        --header 'ctrl-o->open-in-web, enter->git-diff, ctrl-i->checkout' \
        --preview 'echo "CHECKS:"; gh pr checks {1}; echo ""; echo ""; echo "VIEW:"; gh pr view {1}')
key=$(echo "$out" | head -1)
pr=$(echo "$out" | tail -1)
if [ -n "$pr" ]; then
    prnum=$(echo "$pr" | awk '{print $1}')
    case "$key" in
        "ctrl-o") gh pr view --web $prnum ;;
        "ctrl-i") gh pr checkout $prnum ;;
        *) gh pr diff $prnum ;;
    esac
fi
