#!/bin/sh

# FZF + hass-cli

[ -z $HASS_TOKEN ] && echo "HASS_TOKEN is not set!" && exit 1

usage () { echo 'Usage: fhass [ -h(help) ]'; }

while getopts 'h' x; do
    case $x in
        h) usage && exit 1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

preview_cmd="entity=\$(echo {} | awk '{print \$1}'); hass-cli --output yaml --server http://127.0.0.1:8123 entity list \$entity"
FZF_DEFAULT_COMMAND= FZF_DEFAULT_COMMAND="hass-cli --token $HASS_TOKEN state list"
# state_cmd="hass-cli --token $HASS_TOKEN state list"
# entity_cmd="hass-cli --token $HASS_TOKEN entity list"

out=$(fzf +m --height 100% --header-lines=1 \
    --header='ctrl-r->refresh states, ctrl-s->refresh entities' \
    --bind "ctrl-r:reload(${state_cmd})" \
    --preview "$preview_cmd")

echo $out
