#!/bin/sh

# FIND-MULTI-HARDLINKS: look for any files with more than one hardlink in a dir and print it out

# using find(linux):       find . -links +1 -type f -name '*' -printf '%i %p\n' | sort
[ -d "$1" ] || { echo "$1 not a directory!" && return 1; }

if [ "$(uname)" = "Darwin" ]; then
    fd . -t f "$1" -x sh -c 'num=$(stat -f %l "{}"); (( "$num" > 1 )) && stat -f "%i %N" "{}" ' | sort -V
else
    fdfind . -t f "$1" -x bash -c 'num=$(stat -c %h "{}"); (( "$num" > 1 )) && stat -c "%i %n" "{}" ' | sort -V
fi
