#!/bin/sh

# fuzzy move many files to dest dir, handles spaces in paths and git moves, tested with zsh and bash

# TODO: should i use arrays?, maybe just a string with IFS

IFS=$'\n'
files=($(fzf))
echo "$(tput setaf 2)FILES TO BE MOVED:$(tput sgr0)"

for i in ${files[@]}; do echo "    $(tput setaf 3)$i"; done
dest=$(fd --type d | fzf --no-multi)
[ -z "$dest" ] && return 1

mvcmd="mv"; git rev-parse --git-dir > /dev/null 2>&1 && mvcmd="git mv"

for i in ${files[@]}; do eval "$mvcmd $i $dest"; done
echo "$(tput setaf 2)FILES MOVED TO DIR: $(tput setaf 6)$dest$(tput sgr0)"
