#!/bin/sh

# FPS - Fzf over ps processes

usage () { echo "Usage: fps [ -h(help) ] [ -j FZF_HEIGHT ] "; }

while getopts 'hj:' x; do
    case $x in
        h) usage && exit 1 ;;
        j) FZF_HEIGHT="$OPTARG" ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

FZF_HEIGHT=${FZF_HEIGHT:=100}

FZF_DEFAULT_COMMAND="ps -hef"
[ $(uname) = "Linux" ] && FZF_DEFAULT_COMMAND="ps auxhf"

# TODO: /proc/x only works on Linux, fix for OSX
prev_cmd='ls -l /proc/$(echo {} | awk '\''{print $2}'\'')/fd'

fzf --bind "ctrl-r:reload($FZF_DEFAULT_COMMAND)" \
    --header 'Press CTRL-R to reload' --header-lines=1 \
    --height "$FZF_HEIGHT"% --layout=reverse \
    --preview "$prev_cmd" \
    --preview-window=:wrap
