#!/bin/sh

# FZF over systemd running units and do things to it

usage () { echo "Usage: fsysmd [ -f(fzf half screen) ] [ -h(help) ]"; }

FZF_HEIGHT=100
while getopts 'hf' x; do
    case $x in
        h) usage && exit 1 ;;
        f) FZF_HEIGHT=50 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

# preview_cmd='SYSTEMD_COLORS=1 systemctl status $(echo {} | awk '\''{print $1}'\'')'
preview_cmd='unit=$(echo {} | awk '\''{print $1}'\''); SYSTEMD_COLORS=1 systemctl status $unit; echo; SYSTEMD_COLORS=1 systemctl list-dependencies $unit'
preview_cmd_2='unit=$(echo {} | awk '\''{print $1}'\''); SYSTEMD_COLORS=1 systemctl cat $unit'
out=$(systemctl | fzf --height "$FZF_HEIGHT"%  +m --nth=1 --header-lines=1 \
    --header='ctrl-i->restart, ctrl-o->journalctl-follow, ctrl-space->status, ctrl-y->stop, ctrl-s->preview-unit-source' \
    --expect='ctrl-o,ctrl-i,ctrl-space,ctrl-y' \
    --bind "ctrl-s:preview(${preview_cmd_2})" \
    --preview "$preview_cmd")

key=$(echo "$out" | head -1)
unitline=$(echo "$out" | tail -1)
if [ -n "$unitline" ]; then
    unit=$(echo "$unitline" | awk '{print $1}')
    case "$key" in
        "ctrl-o") journalctl -f -u "$unit" ;;
        "ctrl-space") systemctl status "$unit" ;;
        "ctrl-i") sudo systemctl restart "$unit" ;;
        "ctrl-y") sudo systemctl stop "$unit" ;;
    esac
fi
echo "$unit"
