#!/bin/sh

# FV - Fzf on shell variables

usage () { echo "Usage: fv [ -h(help) ] [ -e(EXPORTed vars only)"; }

while getopts 'he' x; do
    case $x in
        h) usage && exit 1 ;;
        e) EXPORT_ONLY=1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

if [ -n "$EXPORT_ONLY" ]; then
    cmd="export"
else
    cmd="typeset"  # zsh
    # cmd="set -o posix; set"  # bash
fi

vars=$(eval "$cmd")

out=$(echo "$vars" | fzf +m \
    --header='ctrl-y->pbcopy_value' \
    --expect='ctrl-y')
key=$(echo "$out" | head -1)
variable=$(echo "$out" | tail -1)
if [ -n "$variable" ]; then
    case "$key" in
        "ctrl-y")
            echo "$(tput setaf 2)RAW FZF LINE: $(tput sgr0) $variable"
            # last 2 seds to strip the double quotes surrounding value
            value=$(echo "$variable" | sed 's/^[^=]*=//' | sed 's/^.//' | sed 's/.$//')
            echo "$(tput setaf 2)VALUE: $(tput bold)"$value" $(tput sgr0)copied to clipboard"
            echo "$value" | pbcopy
            ;;
        *) echo "$variable" ;;
    esac
fi
