#!/bin/sh

# TODO: CLICOLOR_FORCE doesnt seem to be working for osx ls preview

fdname="fd"; [ `uname` = "Linux" ] && fdname="fdfind"

if [ "$(uname)" = "Linux" ]; then
    prev_cmd='ls -hal --color=always {} | awk '\''{$1=$2=$3=$4=""; print $0}'\'' | tail -n+4; echo; jq -C . {}/metadata.json'
else
    prev_cmd='CLICOLOR_FORCE=1 ls -hal {} | awk '\''{$1=$2=$3=$4=""; print $0}'\'' | tail -n+4; echo; jq -C . {}/metadata.json'
    # prev_cmd='CLICOLOR_FORCE=1 ls -hal {}'
fi

out=$($fdname --type d -d 1 | fzf +m --exit-0 \
    --header 'ctrl-i->vim' \
    --expect 'ctrl-i' \
    --preview-window=bottom:40% \
    --preview "$prev_cmd")
key=$(echo "$out" | head -1)
moviedir=$(echo "$out" | tail -1)

if [ -n "$moviedir" ]; then
    case "$key" in
        "ctrl-i") eval "${EDITOR:-vin} $moviedir/metadata.json" ;;
    esac
fi
echo "$file"
