#!/bin/sh

# make a simple java project for scripting and be able to run it

usage() { echo 'Usage: java-ramrom [ -h(help) ] [ -c(create project) ] [ -p PROJECT_NAME ] '; }

while getopts 'hcp:' x; do
    case $x in
        h) usage && exit 1 ;;
        c) CREATE_PROJECT=1 ;;
        p) PROJECT_NAME="$OPTARG" ;;
        *) echo && usage && exit 1 ;;
    esac
done


generate_new_project() {
    [ -z "$PROJECT_NAME" ] && PROJECT_NAME=my_java_script
    [ -d "$PROJECT_NAME" ] && echo "$PROJECT_NAME dir exists" && exit 1

    mkdir $PROJECT_NAME
    cd $PROJECT_NAME

    FILE_NAME=Main.java

    echo "" > $FILE_NAME
    echo "public class Main {" >> $FILE_NAME
    echo "  public static void main(String[] args) {" >> $FILE_NAME
    echo "      System.out.println(\"HELLO WORLD!\");" >> $FILE_NAME
    echo "  }" >> $FILE_NAME
    echo "}" >> $FILE_NAME

    echo "Main-Class: Main" > manifest.txt
}

compile_and_run() {
    javac *.java
    jar cfm my-java-script.jar manifest.txt *.class
    java -jar my-java-script.jar
}

if [ -n "$CREATE_PROJECT" ]; then
    generate_new_project
else
    compile_and_run
fi


