#!/bin/sh

. ~/rams_dot_files/shell_core_tools.sh || { echo "could not find shell_core_tools.sh" && exit 1; }

# FIXME: osx/sh(detect_shell says bash) doesnt print "alias " prefix for alias names
# bash, print_type says aliases are undefined

# calling $(list_funcs) in cmd substitution removes new lines, and IFS= trick gives me "cmd too long" error
if [ $(detect_shell) = "zsh" ]; then
    func_cmd="functions"; [ -n "$funcname" ]  && func_cmd='print -l ${(ok)functions}'
    alias_cmd="alias"; [ -n "$aliasname" ]  && alias_cmd='alias | cut -d= -f1'
    executables=$(hash | cut -d= -f1)
    { eval $alias_cmd; eval $func_cmd; echo "$executables"; } | grep "$1"
else # Assuming BASH
    # NOTE: set prints much more than defined functions, like env vars
    func_cmd="set"; [ -n "$funcname" ]  && func_cmd="typeset -F | awk '{print \$3;}'"
    alias_cmd="alias | cut -c 7-"; [ -n "$aliasname" ]  && alias_cmd='alias | cut -d= -f1 | cut -c 7-'
    executables=$(compgen -c)
    { eval $alias_cmd; eval $func_cmd; echo "$executables"; } | grep "$1"
fi
