#!/bin/sh

# from https://serverfault.com/questions/661978/displaying-a-remote-ssl-certificate-details-using-cli-tools
[ -z "$1" ] && echo "need first arg for hostname" && return 1
echo | openssl s_client -showcerts -servername $1 -connect $1:443 2>/dev/null | \
    openssl x509 -inform pem -noout -text

