#!/bin/sh

print_n_space() {
    i=0
    while [ "$i" -le $1 ]; do
        printf "-"
        i=$(( i + 1 ))
    done
}

paired_devices=$(bluetoothctl devices Paired)

# echo "$paired_devices"

IFS="
"
# IFS=$'\n'
for dev in $paired_devices; do
    printf "$dev"
    dev_id_val_size=${#dev}
    dev_id=$(echo "$dev" | awk '{print $2}')
    dev_info=$(bluetoothctl info "$dev_id")
    connected=$(echo "$dev_info" | grep Connected | awk '{print $2}')
    case "$connected" in
        yes) color=green ;;
        no) color=yellow ;;
        *) color=red ;;
    esac
    padding=$((50 - $dev_id_val_size))
    print_n_space $padding
    # printf ' %.0s' {1..$padding}
    echo " : Connected: $(ansi256 -f $color $connected)"
done
