#!/bin/sh

[ ! "$(uname)" = "Darwin" ] && echo "$(tput setaf 1) Only works in OSX" && exit 1

osascript -e 'tell application "Spotify"' -e 'if sound volume is less than 70 then' \
          -e 'set sound volume to (sound volume + 10)' \
          -e 'end if' -e 'end tell'
