#!/bin/sh

. ~/rams_dot_files/shell_core_tools.sh || { echo "could not find shell_core_tools.sh" && exit 1; }

caller=$0 cmds_defined tmux-version tmux_main_status || exit 1

ver=$(tmux-version)
[ $(echo "$ver < 2.9" | bc) -eq 1 ] && \
    echo "$(tput setaf 1)multi-line status unsupported in version $ver!" && exit 1
[ "$1" = "off" ] && tmux_status_reset
if [ "$1" = "on" ]; then
    tmux set status-interval 5
    tmux set status 2
    tmux_main_status        # set first line, which runs the master script
fi
