#!/bin/sh

# NOTE: with uptime based usage, can go >100%
# NOTE: uptime always uses d.dd format, so remove '.' will result in x100 integer

if [ $(uname) = "Darwin" ]; then
    numcpu=$(sysctl -n hw.ncpu)
else  # assume linux otherwise
    numcpu=$(grep -c processor /proc/cpuinfo)
fi

# NOTE: bash $(()) doesnt like leading zeros, e.g. $(( 078 / 16)) caused an error, but many numbers its ok...
minave=$(uptime | grep --color=never -Eo ":\s[0-9]{1,2}\.[0-9]*" | cut -c 3- | tr -d . | sed 's/^0*//') #1min ave
minave="${minave:=0}"   # edge case: if uptime is 0.00, we will have null value

# local fifteenminave=$(uptime | grep --color=never -o "[0-9]{1,2}\.[0-9]*$" | tr -d .) #15min ave
# TODO: need to cut space at end of line
# local fiveminave=$(uptime | grep --color=never -o "[0-9]\s[0-9]\.[0-9]*\s" | cut -c 3- | tr -d .)

minavepercent=$(($minave / $numcpu))
echo $minavepercent
