#!/bin/bash

##### wrapper for all the various ways I want to start vi

# if we passed in args just run nvim normally
[ -n "$1" ] && nvim "$@" && exit

echo "VIM MODES:"
echo "   n -->  NO_NOICE=1 nvim"
echo "   p -->  VIM_NOPLUG=1 nvim           - simple, don't load plugins"
echo "   u -->  nvim -u NONE                - super simple, done load any rc file"
echo "   l -->  NO_LSP=1 nvim"
echo "   a -->  NO_LSP_AUTOSTART=1 nvim"
echo "   f -->  NVIM_APPNAME=nvimfire nvim"
echo "   e -->  NO_NOICE=1 nvim -e          - start in Ex mode, disable noice as it interferes"
echo '   s -->  [ -f MyCurrentVimSession.vim ] && nvim -S MyCurrentVimSession.vim || echo "no MyCurrentVimSession.vim file!'
echo '   v -->  nvim (no mods)'
echo
read -n1 -p "vim mode: " modesel
echo

case "$modesel" in
    "n") NO_NOICE=1 nvim;;
    "e") NO_NOICE=1 nvim -e;;
    "l") NO_LSP=1 nvim;;
    "u") nvim -u NONE;;
    "p") VIM_NOPLUG=1 nvim;;
    "a") NO_LSP_AUTOSTART=1 nvim;;
    "f") NVIM_APPNAME=nvimfire nvim;;
    "s") [ -f MyCurrentVimSession.vim ] && nvim -S MyCurrentVimSession.vim || echo "no MyCurrentVimSession.vim file!";;
    "v") nvim;;
    *) echo "\`${modesel}\` not valid option" ;;
esac
