#!/bin/bash

##### wrapper for all the various ways I want to start vi

# if we passed in args just run nvim normally
[ -n "$1" ] && nvim "$@" && exit

echo "VIM MODES:"
echo "   $(tput setaf 1)Q$(tput sgr0) -->  EXIT"
echo "   $(tput setaf 3)V$(tput sgr0) -->  nvim                         - no mods"
echo "   $(tput setaf 2)N$(tput sgr0) -->  NO_NOICE=1 nvim"
echo "   $(tput setaf 2)P$(tput sgr0) -->  VIM_NOPLUG=1 nvim           - simple, don't load plugins"
echo "   $(tput setaf 2)U$(tput sgr0) -->  nvim -u NONE                - super simple, done load any rc file"
echo "   $(tput setaf 2)L$(tput sgr0) -->  NO_LSP=1 nvim"
echo "   $(tput setaf 2)A$(tput sgr0) -->  NO_LSP_AUTOSTART=1 nvim"
echo "   $(tput setaf 2)F$(tput sgr0) -->  NVIM_APPNAME=nvimfire nvim"
echo "   $(tput setaf 2)E$(tput sgr0) -->  NO_NOICE=1 nvim -e          - start in Ex mode, disable noice as it interferes"
echo "   $(tput setaf 5)S$(tput sgr0) -->  [ -f MyCurrentVimSession.vim ] && nvim -S MyCurrentVimSession.vim || echo 'no MyCurrentVimSession.vim file!'"
echo
read -n1 -p "vim mode: " modesel
echo

case "$modesel" in
    "n") NO_NOICE=1 nvim;;
    "e") NO_NOICE=1 nvim -e;;
    "l") NO_LSP=1 nvim;;
    "u") nvim -u NONE;;
    "p") VIM_NOPLUG=1 nvim;;
    "a") NO_LSP_AUTOSTART=1 nvim;;
    "f") NVIM_APPNAME=nvimfire nvim;;
    "s") [ -f MyCurrentVimSession.vim ] && nvim -S MyCurrentVimSession.vim || echo "no MyCurrentVimSession.vim file!";;
    "v") nvim;;
    "q") ;;
    *) echo "\`${modesel}\` not valid option" ;;
esac
