#!/bin/sh

# https://n0tablog.wordpress.com/2009/02/09/controlling-vlc-via-rc-remote-control-interface-using-a-unix-domain-socket-and-no-programming/

# seek 100" - goto 100sec after start, "get_time" - current position in seconds since start
# "volume 250" - 250 is 100%, "volume" - return current volume, "volup 10"/"voldown 10" - up/down volume 10 steps
# "info" - codecs/frame-rate/resolution, "stats" - some metrics on data encoded/decoded
# ~/Library/Preferences/org.videolan.vlc/vlcrc contains the perferences config state, including where unix sock is located
# osx: bin to start vlc: /Applications/VLC.app/Contents/MacOS/VLC

# [ "$(uname)" = "Darwin" -a $1 = "launch" ] && /Applications/VLC.app/Contents/MacOS/VLC

vlc_socks_loc=~/vlc.sock
[ ! -S "$vlc_socks_loc" ] && echo "vlc socks file at $vlc_socks_loc not found!" && exit 1
echo $1 | nc -U $vlc_socks_loc
