#!/bin/sh


usage () { echo 'Usage: xscreensaver-toggle [ -h(help) ] [ -v(verbose) ]'; }

while getopts 'hv' x; do
    case $x in
        h) usage && exit 1 ;;
        v) VERBOSE=1 ;;
        *) usage && exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

MODE=$(rg "^mode:\s\s(.*)$" -or '$1' ~/.xscreensaver)

[ -n "$VERBOSE" ] && echo "CURRENT MODE = $MODE"
case "$MODE" in
    off)
        sed -ri 's/^mode:\s\s(.*)$/mode:  random/g' ~/.xscreensaver
        [ -n "$VERBOSE" ] && echo "NEW MODE = random" ;;
    blank|one|random)
        DISPLAY=:1 xscreensaver-command -deactivate
        sed -ri 's/^mode:\s\s(.*)$/mode:  off/g' ~/.xscreensaver
        [ -n "$VERBOSE" ] && echo "NEW MODE = off" ;;
    *)
        echo "GOT MODE = $MODE , either unkown or failed to parse config file" ;;
esac
