#!/bin/bash
# TODO: try to make this sh script

. ~/rams_dot_files/shell_core_tools.sh || { echo "could not find shell_core_tools.sh" && exit 1; }

caller=$0 cmds_defined http || exit 1

resfile=/tmp/yts_movie_links
search_result_file=/tmp/yts_query
printf "\nEnter Query: "; read resultsinput
http --download --output $search_result_file https://yts.mx/ajax/search query=="$resultsinput"
movie_choices=$(jq -r '.data[].title' $search_result_file)
echo ""; [ -z "$movie_choices" ] && echo "! NO RESULTS FOUND FOR QUERY !" && exit 1
echo ""

IFS=$'\r\n'
PS3="select a movie: "
select movie in $movie_choices;
do
    index=($REPLY)
    break;
done

movie_link=$(jq -r --arg INDX $index '.data[($INDX | tonumber) - 1].url' $search_result_file)

http --download --output $resfile "$movie_link"

choices=$(rg -N --color never -o 'href="magnet.*title="([^"]*)"' -r '$1' $resfile)
PS3="select a magnet link: "
select name in ${choices};
do
    index=($REPLY)
    break;
done

num_magnets=$(echo "$choices" | wc -l)
echo "$index" | grep -v "^[[:digit:]]$" > /dev/null && echo "input, $index, is not a single digit!" && exit 1
[ "$index" -gt "$num_magnets" ] && echo "choice value $index, is out of range!" && exit 1

# this get the magnet links themsvles, no color or line numbers
magnet=$(rg -N --color never -o 'href="(magnet[^"]*)"' -r '$1' "$resfile" | sed -n "${index}p")
echo $magnet | sed 's/amp;//g' | pbcopy
echo "UNMODIFIED MAGNET LINK:"
echo $magnet
